/**
 * Which color a subject gets: a department, generic-GIR/HASS/CI, or
 * custom-activity class. The colors themselves are CSS custom properties
 * in departmentColors.css (generated by scripts/generate-palette.mjs).
 */

import type { Subject, SelectedSubject } from "./types";

export const VALID_COURSES = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "14",
  "15",
  "16",
  "17",
  "18",
  "20",
  "21",
  "21A",
  "21G",
  "21H",
  "21L",
  "21M",
  "21T",
  "21W",
  "22",
  "24",
  "CC",
  "CMS",
  "CSB",
  "EC",
  "EM",
  "ES",
  "HST",
  "IDS",
  "MAS",
  "SCM",
  "STS",
  "WGS",
  "SP",
  "SWE",
  "AS",
  "MS",
  "NS",
];

export const VALID_GENERIC = [
  "PHY1",
  "PHY2",
  "CHEM",
  "BIOL",
  "CAL1",
  "CAL2",
  "LAB",
  "REST",
  "HASS-A",
  "HASS-H",
  "HASS-S",
  "HASS-E",
  "CI-H",
  "CI-HW",
];

/** Entries in the custom-activity palette (--custom-color-N). */
export const CUSTOM_COLOR_COUNT = 42;

/** Department or generic color class for a subject id. */
export function courseColorClassFromId(id: string | undefined): string {
  if (id !== undefined) {
    let course = id.split(".")[0];
    if (course.indexOf("GIR:") >= 0) {
      course =
        course.substring(0, course.indexOf("GIR:")) +
        course.substring(course.indexOf("GIR:") + 4);
    }
    const girAttrs = course
      .split(" ")
      .filter((c) => VALID_GENERIC.indexOf(c) >= 0);
    if (VALID_COURSES.indexOf(course) !== -1) {
      return "course-" + course;
    } else if (girAttrs.length > 0) {
      if (girAttrs.length === 1) {
        const attr = girAttrs[0];
        if (attr.indexOf("HASS") === 0 || attr.indexOf("CI") === 0) {
          return "generic-" + course;
        }
      }
      return "generic-GIR";
    }
  }
  return "course-none";
}

/**
 * Palette class for a custom-activity color reference ("@0" ... "@41"),
 * or undefined when the value names no palette entry. `custom_color` is
 * untrusted (imports and cloud payloads carry any JSON), so a non-string
 * or out-of-range value falls back to the department color.
 */
function paletteClass(customColor: unknown): string | undefined {
  if (typeof customColor !== "string") {
    return undefined;
  }
  const index = customColor.slice(1);
  return /^(0|[1-9]\d*)$/.test(index) && Number(index) < CUSTOM_COLOR_COUNT
    ? "custom-color-" + index
    : undefined;
}

/** Whether a value names a real entry in the custom-activity palette. */
export function isCustomColor(value: unknown): value is string {
  return paletteClass(value) !== undefined;
}

/** Color class for a subject (custom activities use their chosen color). */
export function courseColorClass(
  subject: Pick<Subject | SelectedSubject, "subject_id"> & {
    custom_color?: string;
    id?: string;
  },
): string {
  const custom = paletteClass(subject.custom_color);
  if (custom !== undefined) {
    return custom;
  }
  return courseColorClassFromId(subject.id || subject.subject_id);
}

/**
 * CSS color for a subject: a var() into departmentColors.css. Department
 * colors follow the theme; the custom palette is the same in both.
 */
export function courseColor(
  subject: Parameters<typeof courseColorClass>[0],
): string {
  const colorClass = courseColorClass(subject);
  return colorClass.startsWith("custom-color-")
    ? `var(--${colorClass})`
    : `var(--dept-${colorClass})`;
}

/**
 * The value behind a `var(--name)` color, read from the page's styles,
 * for places that need a literal color (an SVG export, a swatch's name).
 * Anything else passes through; an unset variable gives "".
 */
export function resolveCssColor(value: string): string {
  const match = /var\((--[\w-]+)\)/.exec(value);
  if (match === null) {
    return value;
  }
  return getComputedStyle(document.documentElement)
    .getPropertyValue(match[1])
    .trim();
}
